### ISSUE TITLE
Completing Budget class (enhancements)

### ISSUE THREAD

**Issue by tehwenyi** [CS2103-AY1819S2-W17-4/main#45]
Budget currently doesn't have endDate and is not linked to the expenses list. There are also enhancements that should be done.

Tasks:
- [x] Calculate endDate for each Budget created based on startDate and period (in terms of days).

- [x] Allow Budget to calculate the remaining number of days before the cycle repeats from the last expense.

- [x] Allow Budget to calculate the amount user can spend before overspending based on the last expense.

- [x] Allow Budget to create a new similar Budget when the endDate is over, with the same amount and period but different startDate and endDate.

- [x] Calculate remainingDays in Budget (after addExpense is done)

- [x] Fix UI for Budget so that updates will be shown. 

- [x] Currently, viewBudget does not take into account expenses that are already present in the list. Will have to fix this, but need to wait for Date to be incorporated into addExpense first.

**Comment by rahulb99** [comment]
for the 4th task, should we make some class variables for total amount spent (overall and by categories) like `totalAmount` in the Budget class?

**Comment by rahulb99** [comment]
@tehwenyi you made some changes like where you changed number of weeks to days in setBudget, but it's not reflected in the User guide now. 
also whats the difference between `forecast` and `setBudget` ?

@tehwenyi

**Comment by tehwenyi** [comment]
@rahulb99 I've updated the User Guide accordingly after reading your comment! (: I've removed forecast as well as it's likely I'm not doing that
